name: CI/CD

on: push

jobs:
  docker-build-test-deploy:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.set.outputs.test }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build
        run: |
          sudo docker build ./  -t seccubi/logger:latest
      - name: push
        run: sudo docker push seccubi/logger:latest
